### ISSUE TITLE
blueprint show -s indexerror

### ISSUE THREAD

**Issue by alexnesbitt** [devstructure/blueprint#101]
running on ubunto-10.04.3

alex@alex-ubuntu:~$ blueprint show -S myserver
Traceback (most recent call last):
  File "/usr/bin/blueprint-show", line 66, in <module>
    filename = getattr(b, options.generate)(options.relaxed).dumpf()
  File "/usr/lib/python2.6/dist-packages/blueprint/**init**.py", line 463, in sh
    return frontend.sh.sh(self, relaxed, server, secret)
  File "/usr/lib/python2.6/dist-packages/blueprint/frontend/sh.py", line 186, in sh
    service=service)
  File "/usr/lib/python2.6/dist-packages/blueprint/**init**.py", line 493, in walk
    walk.walk(self, *_kwargs)
  File "/usr/lib/python2.6/dist-packages/blueprint/walk.py", line 27, in walk
    walk_files(b, *_kwargs)
  File "/usr/lib/python2.6/dist-packages/blueprint/walk.py", line 96, in walk_files
    callable(pathname, f)
  File "/usr/lib/python2.6/dist-packages/blueprint/frontend/sh.py", line 113, in file
    s.add(_commands, stdin=f['content'], stdout=pathname)
  File "/usr/lib/python2.6/dist-packages/blueprint/frontend/sh.py", line 257, in add
    self.out.append(command(_args, **kwargs))
  File "/usr/lib/python2.6/dist-packages/blueprint/frontend/sh.py", line 208, in command
    '' if '\n' == stdin[-1] else '\n',
IndexError: string index out of range

**Comment by rcrowley** [comment]
Thanks for reporting this, Alex.

**Comment by alexnesbitt** [comment]
thanks for fixing it.
