### ISSUE TITLE
failure in pypi.py on pattern_manager

### ISSUE THREAD

**Issue by drewp** [devstructure/blueprint#113]
dirname is '/usr/lib/python/dist-packages', globname is '/usr/lib/python*/dist-packages'

Traceback (most recent call last):
  File "bin/blueprint-create", line 60, in <module>
    b = blueprint.cli.create(options, args)
  File "/home/drewp/dl/blueprint/local/lib/python2.7/site-packages/blueprint/cli.py", line 32, in create
    b = blueprint.Blueprint.create(args[0])
  File "/home/drewp/dl/blueprint/local/lib/python2.7/site-packages/blueprint/**init**.py", line 72, in create
    getattr(backend, funcname)(b, r)
  File "/home/drewp/dl/blueprint/local/lib/python2.7/site-packages/blueprint/backend/pypi.py", line 43, in pypi
    manager = pattern_manager.search(dirname).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Changing + to \* in the regexp seemed to fix it

**Comment by rcrowley** [comment]
@drewp Am I right in thinking your Python installation is in `/usr/lib/python` (and `/usr/lib/python/dist-packages` instead of `/usr/lib/python2.7` (or whatever version you're using)?  If so, b7b851629b52e40fcb9bd1ec84174867d6a49c9f should address your problem.

**Comment by drewp** [comment]
Looks right, thanks. I'm not sure why I didn't get that code in my test.
