### ISSUE TITLE
blueprint create <hostname> fails on RHEL 6.4

### ISSUE THREAD

**Issue by shawn-m-adams** [devstructure/blueprint#143]
Good morning.

when running "blueprint create" on newly installed blueprint (git cloned and installed yesterday) I get;
# blueprint create lhn
# [blueprint] using cached blueprintignore(5) rules
# [blueprint] searching for PEAR/PECL packages
# [blueprint] searching for software built from source
# [blueprint] searching for Yum packages
# [blueprint] searching for APT packages

Traceback (most recent call last):
  File "/usr/local/bin/blueprint-create", line 84, in <module>
    b = blueprint.cli.create(options, args)
  File "/usr/lib/python2.6/site-packages/blueprint/cli.py", line 32, in create
    b = blueprint.Blueprint.create(args[0])
  File "/usr/lib/python2.6/site-packages/blueprint/**init**.py", line 69, in create
    getattr(backend, funcname)(b, r)
  File "/usr/lib/python2.6/site-packages/blueprint/backend/apt.py", line 22, in apt
    stdout = fnull, stderr = fnull)
  File "/usr/lib64/python2.6/subprocess.py", line 478, in call
    p = Popen(_popenargs, *_kwargs)
  File "/usr/lib64/python2.6/subprocess.py", line 639, in **init**
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1228, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by shawn-m-adams** [comment]
applying the indicated changes did not fix the issue.

**Comment by shawn-m-adams** [comment]
What do you need from me next?
