### ISSUE TITLE
blueprint failing on an attempt at migration (tyan S3970's/Ubuntu 12.04)

### ISSUE THREAD

**Issue by DiagonalArg** [devstructure/blueprint#144]
I'm getting a failure, trying to migrate a blueprint from one Tyan-S3970 running Ubuntu 12.04 to another S3970 (nearly identical, save for an extra quad core CPU).  Both are fully updated machines.  I am trying to migrate the modifications I have made on one to the other.

If there is anything else I can provide, let me know!

/DA

sudo blueprint apply Tyan-Migration
Traceback (most recent call last):
File "/usr/bin/blueprint-apply", line 38, in 
filename = b.sh(options.relaxed).dumpf()
File "/usr/lib/python2.7/dist-packages/blueprint/frontend/sh.py", line 333, in dumpf
f.write('{0}\n'.format(out))
File "/usr/lib/python2.7/codecs.py", line 691, in write
return self.writer.write(data)
File "/usr/lib/python2.7/codecs.py", line 351, in write
data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 35302: ordinal not in range(128)

**Comment by DiagonalArg** [comment]
Made some error with the title.  Should have been:
"blueprint failing on an attempt at migration (tyan S3970's/Ubuntu 12.04)"
