### ISSUE TITLE
Unable to push Blueprint 

### ISSUE THREAD

**Issue by sudhakarteki** [devstructure/blueprint#158]
Hi Sir,

I am unable to push the Blueprint to internet from my cent OS 6.8. Do i need to configure anything else here. I am using Azure Linux machine VM.

**[user@BluePrintDev ~]$ blueprint-push  sample_bp**

Traceback (most recent call last):
  File "/usr/bin/blueprint-push", line 33, in <module>
    secret = blueprint.io.secret(server)
  File "/usr/lib/python2.6/site-packages/blueprint/io/**init**.py", line 112, in secret
    r = http.get('/secret', server=server)
  File "/usr/lib/python2.6/site-packages/blueprint/io/http.py", line 39, in get
    c.request('GET', path, None, headers)
  File "/usr/lib64/python2.6/httplib.py", line 936, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.6/httplib.py", line 973, in _send_request
    self.endheaders()
  File "/usr/lib64/python2.6/httplib.py", line 930, in endheaders
    self._send_output()
  File "/usr/lib64/python2.6/httplib.py", line 802, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.6/httplib.py", line 761, in send
    self.connect()
  File "/usr/lib64/python2.6/httplib.py", line 1134, in connect
    sock = socket.create_connection((self.host, self.port), self.timeout)
  File "/usr/lib64/python2.6/socket.py", line 567, in create_connection
    raise error, msg
socket.error: [Errno 110] Connection timed out
[user@BluePrintDev ~]$

**Comment by rcrowley** [comment]
Hi there,

This service hasn't been operational for over four years.

Thanks for stopping by,

Richard
