### ISSUE TITLE
'ascii' codec can't decode byte 

### ISSUE THREAD

**Issue by sudhakarteki** [devstructure/blueprint#159]
Hi Sir,

I have created blueprint after install gedit tool on my linux system(Azure VM with Cent OS).
when i ran the blueprint-show command ,  it is throwing below error message.

Please let me know how to fix this issue

Step 1 - sudo yum install gedit

Step 2 - sudo blueprint-show -S sample_BP

Traceback (most recent call last):
  File "/usr/bin/blueprint-show", line 63, in <module>
    filename = getattr(b, options.generate)(options.relaxed).dumpf()
  File "/usr/lib/python2.6/site-packages/blueprint/frontend/sh.py", line 333, in dumpf
    f.write('{0}\n'.format(out))
  File "/usr/lib64/python2.6/codecs.py", line 691, in write
    return self.writer.write(data)
  File "/usr/lib64/python2.6/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 4373: ordinal not in range(128)
[user@BluePrintProd tmp]$

**Comment by jameswomack** [comment]
I have the same issue
