### ISSUE TITLE
Crash when reversing my laptop -- Unicode related

### ISSUE THREAD

**Issue by padenot** [devstructure/blueprint#26]
Command : `blueprint create -S plop`
Output : 

```
   [blueprint] searching for Python packages
   [blueprint] searching for software built from source
   [blueprint] /usr/local caused EPERM - try running as root
   [blueprint] searching for Ruby gems
   [blueprint] searching for PEAR/PECL packages
   [blueprint] searching for apt packages
   [blueprint] searching for apt packages to exclude
   [blueprint] caching excluded apt packages
   [blueprint] searching for configuration files
   Initialized empty Git repository in /home/paul/.blueprints.git/
   Traceback (most recent call last):
     File "/usr/local/bin/blueprint-create", line 58, in <module>
       filename = getattr(b, options.generate)().dumpf()
     File "/usr/local/lib/python2.6/dist-packages/blueprint/__init__.py", line 510, in sh
       s.add('{0} >"{1}" <<{2}', command, pathname, eof)
     File "/usr/local/lib/python2.6/dist-packages/blueprint/sh.py", line 29, in add
       self.out.append(u'{0}\n'.format(s).format(*args))
   UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 67: ordinal not in range(128)
```

Python 2.6.6 on Ubuntu 10.10, using latest master.

**Comment by hedgehog** [comment]
I'm seeing something similar on 10.04 when requesting Chef output

```
# [blueprint] searching for apt packages
# [blueprint] searching for configuration files
# [blueprint] searching for Ruby gems
# [blueprint] searching for PEAR/PECL packages
# [blueprint] searching for Python packages
# [blueprint] searching for software built from source
# [blueprint] /usr/local caused EPERM - try running as root
Initialized empty Git repository in /home/hedge/.blueprints.git/
```

**Comment by rcrowley** [comment]
@padenot I don't know if you can still cause this error but do you happen to use Latin-1 characters in pathnames anywhere in `/etc` on your systems?  2b5f58c097b9b84845c48c14791e2bff9ca8173c keeps those from crashing Blueprint but it's far from a complete solution.

**Comment by padenot** [comment]
Indeed I had accentuated characters in my /etc directory. I tested the last tip, and it works like a charm.
