### ISSUE TITLE
chef build fails and tanks server

### ISSUE THREAD

**Issue by BrianTheCoder** [devstructure/blueprint#57]
when I try and build my server config for chef, the build fails, and towards the end goes well over a 1gb of memory consumption. any ideas?

```
app@ip-10-202-57-250:~$ sudo blueprint create -C phobos_server
[sudo] password for app: 
# [blueprint] searching for APT packages to exclude
No packages found matching installation-report.
No packages found matching linux-generic-pae.
No packages found matching language-pack-en.
No packages found matching linux-server.
No packages found matching ubuntu-desktop.
No packages found matching language-pack-gnome-en.
# [blueprint] caching excluded APT packages
# [blueprint] searching for Yum packages to exclude
# [blueprint] searching for PEAR/PECL packages
# [blueprint] searching for software built from source
# [blueprint] searching for configuration files
# [blueprint] searching for Ruby gems
# [blueprint] searching for APT packages
# [blueprint] searching for Yum packages
# [blueprint] searching for Python packages
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-create", line 69, in <module>
    filename = getattr(b, options.generate)().dumpf()
  File "/usr/local/lib/python2.7/dist-packages/blueprint/__init__.py", line 442, in chef
    content = git.content(blob)
  File "/usr/local/lib/python2.7/dist-packages/blueprint/git.py", line 122, in content
    status, stdout = git('show', blob)
  File "/usr/local/lib/python2.7/dist-packages/blueprint/git.py", line 62, in git
    raise GitError(p.returncode)
blueprint.git.GitError: -9
```

**Comment by rcrowley** [comment]
Hi Brian.  What do you mean by "tanks server"?  Another person has reported a similar error as #54.  What version of Git is installed?  What Linux distribution and version are you using?  Could you run this bit of code and reply with its output, please?

```
export BLUEPRINT="foo"
git --git-dir="$HOME/.blueprints.git" ls-tree "$BLUEPRINT" >/tmp/debugging-tree
echo "git ls-tree: $?"
export BLOB="$(grep blueprint.json </tmp/debugging-tree | cut -f1 | cut -d" " -f3)"
rm -f /tmp/debugging-tree
echo "BLOB: $BLOB"
git --git-dir="$HOME/.blueprints.git" show "$BLOB" | head
echo "git show: $?"
```

**Comment by BrianTheCoder** [comment]
towards the final steps of the build, it starts eating up all of the cpu and memory on the server. I am forced to reboot. Watching the processes, it looks like its the blueprint-create process itself and a git process that is spawned. git 1.7.4.1. Using ubuntu 11.04.

I tried the output, but on the second command got 

```
fatal: Not a valid object name foo
```

third line

```
echo "git ls-tree: $?" > git ls-tree: 128
echo "BLOB: $BLOB" > BLOB:
next line
fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions
echo "git show: $?" > git show: 0
```

**Comment by rcrowley** [comment]
Damn I keep forgetting to mention: replace "foo" in the top line with the name of a blueprint on your system like "phobos_server".

Could I trouble you to run your `blueprint create ...` command on the `loud-git` branch I just pushed (https://github.com/devstructure/blueprint/tree/loud-git)?  I'm having a hell of a time reproducing this issue on any distro.

**Comment by rcrowley** [comment]
I can now reproduce this issue - see #54 - a fix is coming shortly.
