### ISSUE TITLE
OSError on blueprint create

### ISSUE THREAD

**Issue by vortec** [devstructure/blueprint#58]
I installed blueprint on MacOS 10.6.7 and when I try blueprint create I get the following:

Fabian-MacBook-Pro:blueprint fabian$ blueprint create my-first-blueprint
# [blueprint] searching for APT packages to exclude
# [blueprint] searching for Yum packages to exclude
# [blueprint] searching for APT packages
# [blueprint] searching for configuration files
# [blueprint] searching for Ruby gems
# [blueprint] searching for PEAR/PECL packages
# [blueprint] searching for Python packages

Traceback (most recent call last):
  File "/usr/local/bin/blueprint-create", line 56, in <module>
    b = blueprint.Blueprint(name=name, create=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/blueprint/**init**.py", line 66, in **init**
    getattr(backend, funcname)(self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/blueprint/backend/pypi.py", line 113, in pypi
    stderr=subprocess.PIPE)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 679, in **init**
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1228, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Fabian-MacBook-Pro:blueprint fabian$

**Comment by zenmatt** [comment]
Blueprint only works on Linux distributions using Debian or RPM based packaging. We don't anticipate adding OS X support in the short term.
