### ISSUE TITLE
No Such File or Directory when looking for service dependencies

### ISSUE THREAD

**Issue by adrianpike** [devstructure/blueprint#68]
I'm on CentOS 5.3, and Blueprint is dying on a blueprint create with an OSError: [Errno 2] No such file or directory.

Full gist is here: https://gist.github.com/1073008

Let me know if there's any way I can help track this down :)

**Comment by rcrowley** [comment]
_Cross-posted from the above-linked Gist:_

I've never run Blueprint against CentOS 5.3, so I hope this doesn't get painful.

For starters, could I get the output of `sudo env`? I'm particularly interested in the `SUDO_*` variables and `HOME`. This smells like either a permissions- or environment-related bug in how Blueprint reacts to `sudo` so let's try this route first.

**Comment by adrianpike** [comment]
```
        [apps@ip-10-195-219-4 ~]$ sudo env
        audit_log_user_command(): Connection refused
        HOSTNAME=ip-10-195-219-4
        TERM=xterm-color
        HISTSIZE=1000
        LS_COLORS=no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:bd=40;33;01:cd=40;33;01:or=01;05;37;41:mi=01;05;37;41:ex=01;32:*.cmd=01;32:*.exe=01;32:*.com=01;32:*.btm=01;32:*.bat=01;32:*.sh=01;32:*.csh=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.bz=01;31:*.tz=01;31:*.rpm=01;31:*.cpio=01;31:*.jpg=01;35:*.gif=01;35:*.bmp=01;35:*.xbm=01;35:*.xpm=01;35:*.png=01;35:*.tif=01;35:
        MAIL=/var/spool/mail/apps
        INPUTRC=/etc/inputrc
        HOME=/home/apps
        SHELL=/bin/bash
        LOGNAME=root
        USER=root
        USERNAME=root
        PATH=/usr/bin:/bin
        SUDO_COMMAND=/bin/env
        SUDO_USER=apps
        SUDO_UID=500
        SUDO_GID=500
        [apps@ip-10-195-219-4 ~]$ 
```

Shazam!

Trying it without sudo real quick - I'm pretty sure I just ctl-c'ed it once it started giving me EPERMs. Without sudo it works dandy, except for stuff it can't see. :)

Trying it with 
            su -u root bash
 gives the same error, as with sudo, BTW.

**Comment by rcrowley** [comment]
The error's actually in writing the complete blueprint into `~/.blueprints.git`, where that directory is determined by `$HOME`.  I've created a branch called [adrianpike](https://github.com/devstructure/blueprint/tree/adrianpike) that I'd like you to install and run, which will print the details of the particular exception I believe is being squashed silently.  If you could paste in the output of running `sudo blueprint create app` on that branch, I should be able to fix the problem properly.

Thanks for your help in debugging this!

**Comment by adrianpike** [comment]
Ran it twice, you'll see why in a second :)

First time:

```
    [apps@ip-10-195-219-4 blueprint]$ sudo blueprint create app
    audit_log_user_command(): Connection refused
    # [blueprint] searching for PEAR/PECL packages
    # [blueprint] searching for Ruby gems
    # [blueprint] searching for configuration files
    # [blueprint] searching for software built from source
    # [blueprint] searching for APT packages
    # [blueprint] searching for Python packages
    # [blueprint] searching for Yum packages
    # [blueprint] searching for service dependencies
    OSError(17, 'File exists')
    Traceback (most recent call last):
      File "/usr/local/bin/blueprint-create", line 65, in <module>
        b.commit(options.message or '')
      File "/usr/lib/python2.6/site-packages/blueprint/__init__.py", line 310, in commit
        git.init()
      File "/usr/lib/python2.6/site-packages/blueprint/git.py", line 43, in init
        stderr=sys.stderr)
      File "/usr/lib/python2.6/subprocess.py", line 633, in __init__
        errread, errwrite)
      File "/usr/lib/python2.6/subprocess.py", line 1139, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
    [apps@ip-10-195-219-4 blueprint]$ 
```

So I deleted /home/apps/.blueprints.git/ and ran it again:

```
    [apps@ip-10-195-219-4 blueprint]$ sudo blueprint create app
    audit_log_user_command(): Connection refused
    # [blueprint] using cached blueprintignore rules
    # [blueprint] searching for PEAR/PECL packages
    # [blueprint] searching for Ruby gems
    # [blueprint] searching for configuration files
    # [blueprint] searching for software built from source
    # [blueprint] searching for APT packages
    # [blueprint] searching for Python packages
    # [blueprint] searching for Yum packages
    # [blueprint] searching for service dependencies
    Traceback (most recent call last):
      File "/usr/local/bin/blueprint-create", line 65, in <module>
        b.commit(options.message or '')
      File "/usr/lib/python2.6/site-packages/blueprint/__init__.py", line 310, in commit
        git.init()
      File "/usr/lib/python2.6/site-packages/blueprint/git.py", line 43, in init
        stderr=sys.stderr)
      File "/usr/lib/python2.6/subprocess.py", line 633, in __init__
        errread, errwrite)
      File "/usr/lib/python2.6/subprocess.py", line 1139, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
    [apps@ip-10-195-219-4 blueprint]$ 
```

Not sure why I'm not getting any exception output on the second run - I've got a few minutes between projects so I'm going to quick look at the source and see if I can find anything. :)

**Comment by adrianpike** [comment]
I think I've got it!

```
[apps@ip-10-195-219-4 blueprint]$ which git
/usr/local/bin/git
```

I don't think local's in root's path, so technically we can blame this one on user error ;)

Symlinking now, I'll let you know how it works.

**Comment by adrianpike** [comment]
Success! The entire problem was just because root couldn't find git. :)
