### ISSUE TITLE
first time run on CentOS 5.6 - exception trying to run dpkg-query

### ISSUE THREAD

**Issue by tombardier** [devstructure/blueprint#73]
Hi there,

I seem to be having a problem with blueprint attempting to run dpkg-query on my CentOS 5.6 box.  Is this a bug?

```
[root@linweb05 ~]# blueprint create linweb05
# [blueprint] searching for PEAR/PECL packages
# [blueprint] searching for Python packages
# [blueprint] searching for apt packages
Traceback (most recent call last):
  File "/usr/bin/blueprint-create", line 5, in <module>
    pkg_resources.run_script('blueprint==3.0.2', 'blueprint-create')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/blueprint-3.0.2-py2.6.egg/EGG-INFO/scripts/blueprint-create", line 53, in <module>
    b = blueprint.Blueprint(name=name, create=True)
  File "/usr/lib/python2.6/site-packages/blueprint-3.0.2-py2.6.egg/blueprint/__init__.py", line 66, in __init__
    getattr(backend, funcname)(self)
  File "/usr/lib/python2.6/site-packages/blueprint-3.0.2-py2.6.egg/blueprint/backend/apt.py", line 17, in apt
    close_fds=True, stdout=subprocess.PIPE)
  File "/usr/lib64/python2.6/subprocess.py", line 633, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1139, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I've reproduced this with the latest stable tarball, and with the latest git clone.

```
[root@linweb05 ~]# cat /etc/issue
CentOS release 5.6 (Final)
Kernel \r on an \m

[root@linweb05 ~]# cat /etc/redhat-release 
CentOS release 5.6 (Final)
[root@linweb05 ~]# 

[root@linweb05 ~]# env
HOSTNAME=linweb05.linvh1.fasthosts.co.uk
TERM=xterm
SHELL=/bin/bash
HISTSIZE=1000
SSH_CLIENT=10.44.255.186 34162 22
SSH_TTY=/dev/pts/4
USER=root
LS_COLORS=no=00:fi=00:di=00;34:ln=00;36:pi=40;33:so=00;35:bd=40;33;01:cd=40;33;01:or=01;05;37;41:mi=01;05;37;41:ex=00;32:*.cmd=00;32:*.exe=00;32:*.com=00;32:*.btm=00;32:*.bat=00;32:*.sh=00;32:*.csh=00;32:*.tar=00;31:*.tgz=00;31:*.arj=00;31:*.taz=00;31:*.lzh=00;31:*.zip=00;31:*.z=00;31:*.Z=00;31:*.gz=00;31:*.bz2=00;31:*.bz=00;31:*.tz=00;31:*.rpm=00;31:*.cpio=00;31:*.jpg=00;35:*.gif=00;35:*.bmp=00;35:*.xbm=00;35:*.xpm=00;35:*.png=00;35:*.tif=00;35:
SSH_AUTH_SOCK=/tmp/ssh-Ualwt25115/agent.25115
MAIL=/var/spool/mail/root
PATH=/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
INPUTRC=/etc/inputrc
PWD=/root
LANG=en_US.UTF-8
SHLVL=1
HOME=/root
LOGNAME=root
SSH_CONNECTION=10.44.255.186 34162 10.216.7.4 22
LESSOPEN=|/usr/bin/lesspipe.sh %s
G_BROKEN_FILENAMES=1
_=/bin/env
OLDPWD=/root/blueprint
```

**Comment by rcrowley** [comment]
Support for RPM-based distros like CentOS was added in Blueprint 3.0.3.  I see you're running 3.0.2 in the stack trace above.  Could you paste in a stack trace from latest [master](https://github.com/devstructure/blueprint) or [v3.0.6](https://github.com/devstructure/blueprint/tree/v3.0.6)?
