### ISSUE TITLE
Deal with non-ASCII characters when searching for service deps

### ISSUE THREAD

**Issue by rcrowley** [devstructure/blueprint#77]
As reported by sarguru in IRC:

```
[08:31:06] <sarguru> # [blueprint] searching for service dependencies
[08:31:06] <sarguru> Traceback (most recent call last):
[08:31:06] <sarguru>  File "/usr/bin/blueprint-create", line 61, in <module>
[08:31:06] <sarguru>    b = blueprint.Blueprint(name=name, create=True)
[08:31:06] <sarguru>  File "/usr/lib/python2.6/dist-packages/blueprint/__init__.py", line 75, in __init__
[08:31:06] <sarguru>    services.services(self)
[08:31:08] <sarguru>  File "/usr/lib/python2.6/dist-packages/blueprint/services.py", line 80, in services
[08:31:10] <sarguru>    b.walk_services(service=service)
[08:31:12] <sarguru>  File "/usr/lib/python2.6/dist-packages/blueprint/__init__.py", line 520, in walk_services
[08:31:15] <sarguru>    self.walk_services(managername, **kwargs)
[08:31:18] <sarguru>  File "/usr/lib/python2.6/dist-packages/blueprint/__init__.py", line 530, in walk_services
[08:31:20] <sarguru>    callable(manager, service)
[08:31:22] <sarguru>  File "/usr/lib/python2.6/dist-packages/blueprint/services.py", line 73, in service
[08:31:24] <sarguru>    service_file(manager, service, '/etc/init.d/{0}'.format(service))
[08:31:26] <sarguru>  File "/usr/lib/python2.6/dist-packages/blueprint/services.py", line 43, in service_file
[08:31:28] <sarguru>    if -1 != content.find(dirname):
[08:31:31] <sarguru> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 457: ordinal not in range(128)
```

**Comment by squidfunk** [comment]
I have the exact same error at the moment. Removing the copyright sign (0xC2) from the file fixes it.

**Comment by mcculloughsean** [comment]
Getting a similar error

```
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-create", line 61, in <module>
    b = blueprint.Blueprint(name=name, create=True)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/__init__.py", line 75, in __init__
    services.services(self)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/services.py", line 80, in services
    b.walk_services(service=service)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/__init__.py", line 522, in walk_services
    self.walk_services(managername, **kwargs)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/__init__.py", line 532, in walk_services
    callable(manager, service)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/services.py", line 78, in service
    b.walk_service_files(manager, service, service_file=service_file)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/__init__.py", line 551, in walk_service_files
    callable(manager, servicename, pathname)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/services.py", line 43, in service_file
    if -1 != content.find(dirname):
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 53: ordinal not in range(128)
```

**Comment by squidfunk** [comment]
I traced the errors back and eliminated the specific signs (all of them were inside comments) by putting a

<pre>
print path
</pre>


into  /usr/local/lib/python2.6/dist-packages/blueprint/services.py before the line 

<pre>
if -1 != content.find(dirname):
</pre>


Hope this helps you!
