### ISSUE TITLE
Blueprint not working with big files

### ISSUE THREAD

**Issue by mback2k** [devstructure/blueprint#79]
```
blueprint create my-first-blueprint
# [blueprint] searching for APT packages to exclude
Kein Paket gefunden, das auf wireless-crda passt.
Kein Paket gefunden, das auf os-prober passt.
Kein Paket gefunden, das auf ubuntu-standard passt.
Kein Paket gefunden, das auf installation-report passt.
Kein Paket gefunden, das auf linux-generic-pae passt.
Kein Paket gefunden, das auf language-pack-en passt.
Kein Paket gefunden, das auf ubuntu-minimal passt.
Kein Paket gefunden, das auf linux-server passt.
Kein Paket gefunden, das auf ubuntu-desktop passt.
Kein Paket gefunden, das auf language-pack-gnome-en passt.
Kein Paket gefunden, das auf grub-pc passt.
# [blueprint] caching excluded APT packages
# [blueprint] searching for Yum packages to exclude
# [blueprint] searching for Ruby gems
# [blueprint] searching for APT packages
# [blueprint] searching for PEAR/PECL packages
# [blueprint] searching for configuration files
# [blueprint] searching for Python packages
# [blueprint] searching for software built from source
# [blueprint] searching for Yum packages
# [blueprint] searching for service dependencies
fatal: Cannot handle files this big
Traceback (most recent call last):
  File "/usr/bin/blueprint-create", line 65, in <module>
    b.commit(options.message or '')
  File "/usr/lib/python2.6/dist-packages/blueprint/__init__.py", line 328, in co                                                                                                                           mmit
    git.git('update-index', '--add', os.path.abspath(filename))
  File "/usr/lib/python2.6/dist-packages/blueprint/git.py", line 64, in git
    raise GitError(p.returncode)
blueprint.git.GitError: 128
```

**Comment by rcrowley** [comment]
Hi Marc,

(Long time, no see.)

This appears to be a limitation within Git, not Blueprint per se.  What does `find /etc /usr/local -size +1G` say are the offending files?  Blueprint's definitely not meant to be used to encapsulate data, so potentially ignoring the offending files/directories will get you back on track.  (See http://devstructure.github.com/blueprint/blueprintignore.5.html for syntax details for the `~/.blueprintignore` file.)

**Comment by mback2k** [comment]
Hi Richard,

nice to see you again. Thanks for the tip. It seems like the big file is already gone, because now I am stuck at the ASCII error reported in the other issue. Currently the search does not yield any result.

I will try to identify the big files as soon as the error comes up again.
