### ISSUE TITLE
TypeError: object of type 'int' has no len()

### ISSUE THREAD

**Issue by pshima** [devstructure/blueprint#92]
upon blueprint show -C namehere I am getting a stack trace

Traceback (most recent call last):
  File "/usr/local/bin/blueprint-show", line 62, in <module>
    filename = getattr(b, options.generate)(options.relaxed).dumpf()
  File "/usr/local/lib/python2.6/dist-packages/blueprint/frontend/chef.py", line 299, in dumpf
    self._dump(f.write, inline=False)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/frontend/chef.py", line 278, in _dump
    w(resource.dumps(inline))
  File "/usr/local/lib/python2.6/dist-packages/blueprint/frontend/chef.py", line 388, in dumps
    out.append(u'\t{0} {1}\n'.format(key, self._dumps(value)))
  File "/usr/local/lib/python2.6/dist-packages/blueprint/frontend/chef.py", line 356, in _dumps
    elif 1 < len(value) and ':' == value[0]:
TypeError: object of type 'int' has no len()

Did a quick search around didn't find any answer as to what may have gone wrong here.  Some chef files are generated.

**Comment by pshima** [comment]
What would I do to fix this as all I am doing is running a blueprint show -C against a blueprint I had created?

**Comment by rcrowley** [comment]
@petey5king: Did the fix I pushed above not help?  I reproduced the problem and observed it being fixed with 5bb686583eae887e7ac05b57ddd73cfbbba1b521.
