### ISSUE TITLE
fatal: unable to deflate new object

### ISSUE THREAD

**Issue by abhigupta** [devstructure/blueprint#95]
I am getting following strage error when running blueprint for first time in Ubuntu. Any thoughts?

``` bash
[root@server:~]# blueprint create my-first-blueprint
# [blueprint] using cached blueprintignore(5) rules
# [blueprint] searching for Python packages
# [blueprint] searching for PEAR/PECL packages
# [blueprint] searching for npm packages
# [blueprint] searching for Yum packages
# [blueprint] searching for software built from source
# [blueprint] searching for APT packages
# [blueprint] searching for configuration files
# [blueprint] searching for Ruby gems
# [blueprint] searching for service dependencies
fatal: unable to deflate new object f49ced87bacbe1d5c65390f0b4a6b3bbe734bf3a (-2)
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-create", line 56, in <module>
    b = blueprint.cli.create(options, args)
  File "/usr/local/lib/python2.6/dist-packages/blueprint/cli.py", line 31, in create
    b.commit(options.message or '')
  File "/usr/local/lib/python2.6/dist-packages/blueprint/__init__.py", line 373, in commit
    git.git('update-index', '--add', os.path.abspath(filename))
  File "/usr/local/lib/python2.6/dist-packages/blueprint/git.py", line 83, in git
    raise GitError(p.returncode)
blueprint.git.GitError: 128
```

**Comment by rcrowley** [comment]
This is an error within Git that we're not able to recover from.  Is there a temporary directory like `/tmp/blueprint-XXXXXX` that you can inspect.  If it's there, you should be able to find a tarball in that directory.  Is it corrupted or otherwise unique?
